language: php

php:
  - 5.5
  - 5.6
  - 7

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - helmut@typo3.org

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
